name: 'Setup Core Lightning'
description: 'Set up Core Lightning on the runner'

inputs:
  checkout-version:
    description: 'v23.05.1'
    required: true
    default: 'v23.05.1'

runs:
  using: 'composite'
  steps:
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install dependencies
      run: |
        sudo apt-get install -y autoconf automake build-essential git libtool libgmp-dev libsqlite3-dev python3 python3-pip net-tools zlib1g-dev libsodium-dev gettext valgrind libpq-dev shellcheck cppcheck libsecp256k1-dev jq 
        sudo apt-get remove -y protobuf-compiler
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.12.0/protoc-3.12.0-linux-x86_64.zip
        sudo unzip -o protoc-3.12.0-linux-x86_64.zip -d /usr/local bin/protoc
        sudo unzip -o protoc-3.12.0-linux-x86_64.zip -d /usr/local 'include/*'
        rm -f protoc-3.12.0-linux-x86_64.zip
        sudo chmod 755 /usr/local/bin/protoc
      shell: bash

    - name: Install Python dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install poetry mako
        pip install grpcio-tools
      shell: bash

    - name: Checkout and build lightning
      run: |
        git clone https://github.com/ElementsProject/lightning.git lightning_git
        cd lightning_git
        git checkout ${{ inputs.checkout-version }}
        ./configure --enable-developer --enable-rust
        poetry install
        poetry run make -j `nproc`
      shell: bash
